CREATE TYPE sex_enum AS ENUM (
  'female',
  'male'
);
  
CREATE TYPE family_type_enum AS ENUM (
  'adoption',
  'host',
  'both'
);
  
CREATE TYPE treatment_enum AS ENUM (
  'vaccination_first',
  'vaccination_second',
  'test_fiv',
  'test_felv',
  'deworm',
  'antiparasite_internal',
  'antiparasite_external',
  'corona',
  'giardiasis',
  'ringworm',
  'diarrhea',
  'cat_flu'
  'other'
);

create table
  families (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    address text null,
    email text null,
    phone text null,
    family_type public.family_type_enum null default 'adoption'::family_type_enum,
    constraint families_pkey primary key (id)
  ) tablespace pg_default;

create table
  cats (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    birth_date date null,
    adoption_date date null,
    chipped boolean null default false,
    certificate_healthy boolean null default false,
    health_book boolean null default false,
    sterilised boolean null default false,
    with_dogs boolean null default false,
    with_cats boolean null default false,
    character text null,
    reserved boolean null default false,
    adopted boolean null default false,
    deceased boolean null default false,
    sex public.sex_enum null default 'female'::sex_enum,
    images text null,
    color text null,
    arrival_date date null,
    history text null,
    protocol_date date null,
    care_received text null,
    host_family_id bigint references families,
    adoption_family_id bigint references families,
    chip_id text null,
    notes text null,
    deed_of_transfer boolean null,
    constraint cats_pkey primary key (id),
    constraint cats_adoption_family_id_fkey foreign key (adoption_family_id) references families (id),
    constraint cats_host_family_id_fkey foreign key (host_family_id) references families (id)
  ) tablespace pg_default;

create table
  treatments (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    cat_id bigint null,
    date date null,
    notes text null,
    treatment_type public.treatment_enum null default 'vaccination_first'::treatment_enum,
    treatment_outcome public.treatment_outcome_enum null default 'not_applicable'::treatment_outcome_enum,
    constraint treatments_pkey primary key (id),
    constraint treatments_cat_id_fkey foreign key (cat_id) references cats (id)
  ) tablespace pg_default;

create table
  weights (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    cat_id bigint references cats,
    date date null,
    weight numeric null,
    constraint weights_pkey primary key (id)
  ) tablespace pg_default;